config/routes.rb
Rails.application.routes.draw do

  get 'buglemaster/bugleschedule'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'

  get 'users/new'
  get 'users/create'
  get 'users/profile'
  post 'users/add_schedule', to: 'users#add_schedule'

  get 'spreadsheet/index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create' 
  post 'logout', to: 'sessions#logout'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
#  get "/pages/:page" => "pages#show"

#use resources? https://guides.rubyonrails.org/getting_started.html
  resources :users, only: [:new, :create, :profile]
  resources :cadets, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :cadets, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  root 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cadets.rb
class Cadets < ApplicationRecord
    validates :CWID, presence: true, length: { minimum: 8, maximum: 8}
    validates :CO_ID, presence: true, length: { minimum: 1, maximum: 2}
    validates :C_STATUS, presence: true, length: { minimum: 1, maximum: 1}
    validates :F_NAME, presence: true, length: { minimum: 2, maximum: 20}
    validates :L_NAME, presence: true, length: { minimum: 2, maximum: 20}
    validates :EMAIL, presence: true, length: { minimum: 5, maximum: 50}
    validates :RANK_ID, presence: true, length: { minimum: 1, maximum: 1}
end  

app/controllers/cadets_controller.rb
class CadetsController < ApplicationController
    before_action :set_cadet, only: [:show, :edit, :update, :destroy]
    skip_before_action :has_profile?, only: [:new, :create]
    def show
    end

    def index
        @cadets = Cadets.all
    end

    def new
        @cadet = Cadets.new
    end


    def edit
    end

    def create
        temp_hash = {:CWID => get_cwid(), :CO_ID => get_company_id(), :C_STATUS => get_cadet_status(), :RANK_ID => get_rank()}
        
        @cadet = Cadets.new(cadet_params.merge(temp_hash))
        if @cadet.save
            flash[:notice] = "Cadet was created successfully."
            redirect_to cadet_path(@cadet)
        else
            render 'new'
        end
    end

    def get_cwid()
        return current_user.CWID
    end
    
    def get_cadet_status()
        return ::CStatus.find_by(C_NAME: cadet_params[:C_STATUS]).C_ID
    end
    def get_company_id()
        return ::Company.find_by(CO_NAME: cadet_params[:CO_ID]).CO_ID
    end
    def get_rank()
        return ::Ranks.find_by(RANK_NAME: cadet_params[:RANK_ID]).RANK_ID
    end

    def update
        if @cadet.update(cadets_params)
            flash[:notice] = "Cadet was updated successfully"
            redirect_to cadet_path(@cadet)
        else
            render 'edit'

        end
    end

    def destroy
        @cadet.destroy
        redirect_to cadets_path
    end

    private 
    
    def set_cadet
        @cadet = Cadets.find(params[:id])
    end

    def cadet_params
        params.require(:cadet).permit(:CWID, :CO_ID, :C_STATUS, :F_NAME, :M_INITIAL, :L_NAME, :R_NUM, :P_NUM, :EMAIL, :RANK_ID, :monday, :tuesday, :wednesday, :thursday, :friday)
    end

    def cadets_params
        params.require(:cadets).permit(:CWID, :CO_ID, :C_STATUS, :F_NAME, :M_INITIAL, :L_NAME, :R_NUM, :P_NUM, :EMAIL, :RANK_ID, :monday, :tuesday, :wednesday, :thursday, :friday)
    end
end

app/views/cadets/_form.html.erb
<% if @cadet.errors.any? %>
    <h2> The following errors prevented the page fromt being saved </h2>
    <ul>
        <% @cadet.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
    </ul>
<% end %>

app/views/cadets/edit.html.erb
<h1> Edit a new Cadet </h1>

<%= render 'form' %>


<%= form_with(model: @cadet, local: true) do |f| %>

    <p>
        <%= f.label :First_Name %> <br/>
        <%= f.text_field :F_NAME %>
    </p>

    <p>
        <%= f.label :Middle_Name %> <br/>
        <%= f.text_field :M_INITIAL %>
    </p>

    <p>
        <%= f.label :Last_Name %> <br/>
        <%= f.text_field :L_NAME %>
    </p>

    <p>
        <%= f.label :CWID %> <br/>
        <%= f.text_field :CWID %>
    </p>

    <p>
        <%= f.label :C_Status %> <br/>
        <%= f.text_field :C_STATUS %>
    </p>

    <p>
        <%= f.label :Company_Number %> <br/>
        <%= f.text_field :CO_ID %>
    </p>

    <p>
        <%= f.label :Room_Number %> <br/>
        <%= f.text_field :R_NUM %>
    </p>

    <p>
        <%= f.label :P_NUM %> <br/>
        <%= f.text_field :P_NUM %>
    </p>

    <p>
        <%= f.label :EMAIL %> <br/>
        <%= f.text_field :EMAIL %>
    </p>

    <p>
        <%= f.label :RANK_ID %> <br/>
        <%= f.text_field :RANK_ID %>
    </p>

    <p>
        <%= f.label :Monday_Classes %> <br/>
        <%= f.text_area :monday %>
    </p>

    <p>
        <%= f.label :Tuesday_Classes %> <br/>
        <%= f.text_area :tuesday %>
    </p>

    <p>
        <%= f.label :Wednesday_Classes %> <br/>
        <%= f.text_area :wednesday %>
    </p>

    <p>
        <%= f.label :Thursday_Classes %> <br/>
        <%= f.text_area :thursday %>
    </p>

    <p>
        <%= f.label :Friday_Classes %> <br/>
        <%= f.text_area :friday %>
    </p>

    
    <p>
        <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', cadets_path %>

app/views/cadets/index.html.erb
<body style= "background-color:#d4e3e5;">
<h1>Company Spreadsheet</h1>
<p>I will contain the spreadsheet view for cadet schedules</p>
<style type="text/css">
.tftable {font-size:12px;color:#333333;width:100%;border-width: 1px;border-color: #729ea5;border-collapse: collapse;}
.tftable th {font-size:12px;background-color:#acc8cc;border-width: 1px;padding: 8px;border-style: solid;border-color: #729ea5;text-align:left;}
.tftable tr {background-color:#d4e3e5;}
.tftable td {font-size:12px;border-width: 1px;padding: 8px;border-style: solid;border-color: #729ea5;}
.tftable tr:hover {background-color:#ffffff;}
hr { display: block; margin-top: 1em; margin-bottom: 1em; margin-left: auto; margin-right: auto; border-style: inset; border-width: 1px;} 
</style>

    <table class="tftable" border="1">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th colspan = 3>Actions</th>
            </tr>
        </thead>

        <tbody>
            <tr>
                <% @cadets.each do |cadet| %>
                <td><%= cadet.F_NAME %> </td>
                <td><%= cadet.L_NAME %> </td>
                <td><%= cadet.monday %> </td>
                <td><%= cadet.tuesday %> </td>
                <td><%= cadet.wednesday %> </td>
                <td><%= cadet.thursday %> </td>
                <td><%= cadet.friday %> </td>
                <td> <%= link_to 'Show', cadet_path(cadet) %> </td>
                <td> <%= link_to 'Edit', edit_cadet_path(cadet) %> </td>
                <td> <%= button_to 'Delete', cadet_path(cadet), method: :delete, data: { confirm: "Are you sure?"} %> </td>
            </tr>
            <% end %>
        </tbody> 
    </table>
    
    <p>
        <%= link_to 'Add new cadet', new_cadet_path %>
    </p>
    
    <hr>

    <h1>Guard Roster</h1>
    <table class="tftable" border="1">
    <tbody>

        <thead>
            <tr>
                <th>Times</th>
                <th>Sophomore</th>
                <th>Junior</th>
                <th>Senior</th>
                <th colspan = 3>Actions</th>
            </tr>
            <tr>
               <th id="M0530">0530</th>
            </tr>
            <tr>
               <th id="M0700">0700</th>
            </tr>
            <tr>
               <th id="M0800">0800</th>
            </tr>
            <tr>  
               <th id="M0900">0900</th>
            </tr>
            <tr>
               <th id="M1000">1000</th>
            </tr>
            <tr>
               <th id="M1100">1100</th>
            </tr>
            <tr>
               <th id="M1200">1200</th>
            </tr>
            <tr>
               <th id="M1300">1300</th>
            </tr>
            <tr>
               <th id="M1400">1400</th>
            </tr>
            <tr>
               <th id="M1530">1500</th>
            </tr>
            <tr>
               <th id="M1600">1600</th>
            </tr>
            <tr>
               <th id="M1700">1700</th>
            </tr>
            <tr>
               <th id="M1800">1800</th>
            </tr>
            <tr>
               <th id="M1900">1900</th>
            </tr>
            <tr>
               <th id="M2000">2000</th>
            </tr>
            <tr>
               <th id="M2100">2100</th>
            </tr>
            <tr>
               <th id="M2200">2200</th>
            </tr>
             
        </thead>

     </tbody>   

        <tbody>
            
            <tr>
                <td> Display an array of times </td>
                <td> 1</td>
                <td> 2</td>
                <td> 3</td>
                <td> 4</td>
                <td> 5</td>
                <td> 6</td>
            </tr>
        </tbody> 
    </table>
</body>

app/views/cadets/new.html.erb
<h1> Enter in a new Cadet </h1>

<%= render 'form' %>


<%= form_with scope: :cadet, url: cadets_path, local: true do |f| %>

    <p>
        <%= f.label :First_Name %> <br/>
        <%= f.text_field :F_NAME %>
    </p>

    <p>
        <%= f.label :Middle_Name %> <br/>
        <%= f.text_field :M_INITIAL %>
    </p>

    <p>
        <%= f.label :Last_Name %> <br/>
        <%= f.text_field :L_NAME %>
    </p>

    <p>
        <%= f.label :CWID %> <br/>
        <%= f.text_field :CWID %>
    </p>

    <p>
        <%= f.label :C_Status %> <br/>
        <%= f.text_field :C_STATUS %>
    </p>

    <p>
        <%= f.label :Company_Number %> <br/>
        <%= f.text_field :CO_ID %>
    </p>

    <p>
        <%= f.label :Room_Number %> <br/>
        <%= f.text_field :R_NUM %>
    </p>

    <p>
        <%= f.label :P_NUM %> <br/>
        <%= f.text_field :P_NUM %>
    </p>

    <p>
        <%= f.label :EMAIL %> <br/>
        <%= f.text_field :EMAIL %>
    </p>

    <p>
        <%= f.label :RANK_ID %> <br/>
        <%= f.text_field :RANK_ID %>
    </p>

    <p>
        <%= f.label :Monday_Classes %> <br/>
        <%= f.text_area :monday %>
    </p>

    <p>
        <%= f.label :Tuesday_Classes %> <br/>
        <%= f.text_area :tuesday %>
    </p>

    <p>
        <%= f.label :Wednesday_Classes %> <br/>
        <%= f.text_area :wednesday %>
    </p>

    <p>
        <%= f.label :Thursday_Classes %> <br/>
        <%= f.text_area :thursday %>
    </p>

    <p>
        <%= f.label :Friday_Classes %> <br/>
        <%= f.text_area :friday %>
    </p>

    <p>
        <%= f.submit %>
    </p>

<% end %>

<%= link_to 'Back', cadets_path %>

app/views/cadets/show.html.erb
<h1> Details about <%= @cadet.F_NAME %> <%= @cadet.L_NAME %> </h1>


<p><strong> FIRST NAME: </strong> <%= @cadet.F_NAME %> </p>
<p><strong> MIDDLE NAME: </strong> <%= @cadet.M_INITIAL %> </p>
<p><strong> LAST NAME: </strong> <%= @cadet.L_NAME %> </p>
<p><strong> CWID: </strong> <%= @cadet.CWID %> </p>
<p><strong> EMAIL: </strong> <%= @cadet.EMAIL %> </p> 
<p><strong> RANK ID: </strong> <%= @cadet.RANK_ID %> </p>
<p><strong> COMPANY ID: </strong> <%= @cadet.CO_ID %> </p>
<p><strong> C STATUS: </strong> <%= @cadet.C_STATUS %> </p>
<p><strong> ROOM NUMBER: </strong> <%= @cadet.R_NUM %> </p>
<p><strong> P NUMBER: </strong> <%= @cadet.P_NUM %> </p>

<p><strong> MONDAY CLASSES: </strong> <%= @cadet.monday %>  </p>
<p><strong> TUESDAY CLASSES: </strong> <%= @cadet.tuesday %>  </p>
<p><strong> WEDNESDAY CLASSES: </strong> <%= @cadet.wednesday %>  </p>
<p><strong> THURSDAY CLASSES: </strong> <%= @cadet.thursday %> </p>
<p><strong> FRIDAY CLASSES: </strong> <%= @cadet.friday %> </p>

<%= link_to 'Edit', edit_cadet_path(@cadet) %> |
<%= button_to 'Delete', cadet_path(@cadet), method: :delete, data: { confirm: "Are you sure?"} %> |
<%= link_to 'Back', cadets_path %>